-- 코드를 입력하세요
# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (B.PRICE*SUM(S.SALES)) AS TOTAL_SALES
# FROM BOOK AS B
# JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
# WHERE SALES_DATE LIKE "2022-01%"
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY AUTHOR_ID, CATEGORY DESC

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((B.PRICE*S.BOOK_COUNT)) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS BOOK_COUNT
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE "2022-01%"
    GROUP BY BOOK_ID
) AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC