-- 코드를 작성해주세요
# SELECT ITEM_ID, ITEM_NAME
# FROM ITEM_INFO 
# WHERE ITEM_ID IN 
# (
#     SELECT ITEM_ID 
#     FROM ITEM_TREE
#     WHERE PARENT_ITEM_ID IS NULL
# )
# ORDER BY ITEM_ID;

SELECT II.ITEM_ID, ITEM_NAME
FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID;