-- 코드를 작성해주세요
SELECT YEAR, ROUND(AVG(PM_VAL1),2) AS PM10, ROUND(AVG(PM_VAL2),2) AS "PM2.5"
FROM (
    SELECT YEAR(YM) AS YEAR, PM_VAL1, PM_VAL2
    FROM AIR_POLLUTION
    WHERE LOCATION2 = "수원"
    ORDER BY YEAR
) AS s
GROUP BY YEAR
ORDER BY YEAR;
