-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM (
#     SELECT USER_ID, COUNT(PRODUCT_ID) AS PRODUCT_COUNT, PRODUCT_ID
#     FROM ONLINE_SALE
#     GROUP BY USER_ID, PRODUCT_ID
#     ) AS table_count
# WHERE table_count.PRODUCT_COUNT > 1
# ORDER BY USER_ID, PRODUCT_ID DESC;

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;