-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (table_total.TOTAL_AMOUNT * P.PRICE) AS SALES
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS table_total 
JOIN PRODUCT AS P ON table_total.PRODUCT_ID = P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;