-- 코드를 입력하세요

SELECT *
FROM (
    SELECT CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE_30*0.01),0) AS FEE
    FROM (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = "세단" OR CAR_TYPE = "SUV"
    ) AS C JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE AS DISCOUNT_RATE_30
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = "30일 이상" 
    ) AS P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
    )
) AS T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;