-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),"km") AS AVERAGE_DISTANCE
FROM (
    SELECT DISTINCT LINE, ROUTE, D_BETWEEN_DIST, STATION_NAME
    FROM SUBWAY_DISTANCE
) AS s
GROUP BY ROUTE
ORDER BY CAST(TOTAL_DISTANCE AS UNSIGNED) DESC;