# -- 코드를 입력하세요

WITH T AS(
    SELECT HISTORY_ID, (DAILY_FEE*RENTAL_PERIOD) AS TOTAL_FEE,
        (CASE
            WHEN RENTAL_PERIOD >= 90 THEN 90
            WHEN RENTAL_PERIOD >= 30 THEN 30
            WHEN RENTAL_PERIOD >= 7 THEN 7
            ELSE NULL
        END) AS DURATION_TYPE
    FROM (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = "트럭"
    ) AS C JOIN 
        (
            SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS "RENTAL_PERIOD"
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        ) AS H ON C.CAR_ID = H.CAR_ID
)
SELECT HISTORY_ID, FLOOR((TOTAL_FEE*(1-IFNULL(DISCOUNT_RATE,0)/100))) AS FEE
FROM T LEFT JOIN (
    SELECT CAST(DURATION_TYPE AS UNSIGNED) AS DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = "트럭"
) AS P ON T.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;