-- 코드를 입력하세요
SELECT F.FLAVOR 
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
    FROM FIRST_HALF
    GROUP BY FLAVOR
) AS F 
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SUM
    FROM JULY
    GROUP BY FLAVOR
) AS J ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_SUM + J.TOTAL_SUM) DESC
LIMIT 3