-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE MCDP_CD = "CS" AND APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN = "N"
) AS A
JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
JOIN DOCTOR AS D ON A.MDDR_ID = DR_ID
ORDER BY APNT_YMD