-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM (
    # 서브 쿼리로 중간테이블 레코드 줄이기
    SELECT *
    FROM FISH_NAME_INFO
    WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER"
) AS n
JOIN FISH_INFO AS f ON f.FISH_TYPE = n.FISH_TYPE
WHERE FISH_NAME = "BASS" OR FISH_NAME = "SNAPPER";