-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = "세단"
) AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE MONTH(START_DATE) = 10 
ORDER BY H.CAR_ID DESC;