-- 코드를 입력하세요
# SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
# FROM USED_GOODS_REPLY R
#     JOIN USED_GOODS_BOARD AS B
#     ON R.BOARD_ID = B.BOARD_ID
# WHERE R.CREATED_DATE BETWEEN "2022-10-01" AND "2022-10-31"
# ORDER BY R.CREATED_DATE ASC, B.TITLE ASC
SELECT b.TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS,
    date_format(r.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE 
from USED_GOODS_BOARD b
INNER join USED_GOODS_REPLY r on b.BOARD_ID=r.BOARD_ID
where date_format(b.CREATED_DATE,'%Y-%m') = '2022-10'
order by r.CREATED_DATE,b.TITLE