-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",F.BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
) AS B JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC;